# Generated by Django 3.1.7 on 2021-03-24 14:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_auto_20210324_1420'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 24, 14, 43, 43, 898723), verbose_name='添加时间'),
        ),
    ]
